/**
 * Nomes em português dos metadados do exiftool. Tabela vinda do yazi do André
 * (plugin metadados-pt): campo sem tradução aparece com o nome separado em palavras.
 */

const CAMPOS: Record<string, string> = {
  "ADJDebugInfo": "Depuração interna (ajustes)",
  "AEDebugInfo": "Depuração interna (exposição automática)",
  "AEHistogramInfo": "Histograma (exposição automática)",
  "AELiveViewHistogramInfo": "Histograma (visualização ao vivo)",
  "AELiveViewLocalHistogram": "Histograma local (visualização ao vivo)",
  "AELocalHistogram": "Histograma local (exposição)",
  "AFDebugInfo": "Depuração interna (foco automático)",
  "AVCConfiguration": "Configuração AVC (H.264)",
  "AWBDebugInfo": "Depuração interna (balanço de branco)",
  "About": "Sobre (URI)",
  "AbsoluteAltitude": "Altitude absoluta",
  "Album": "Álbum",
  "AlreadyApplied": "Ajustes já aplicados",
  "AltitudeType": "Tipo de altitude",
  "AndroidCaptureFPS": "Quadros por segundo (Android)",
  "AndroidVersion": "Versão do Android",
  "Aperture": "Abertura",
  "ApertureValue": "Valor de abertura",
  "AppVersion": "Versão do aplicativo",
  "Application": "Aplicativo",
  "Artist": "Autor",
  "AudioBitsPerSample": "Bits por amostra (áudio)",
  "AudioChannels": "Canais de áudio",
  "AudioFormat": "Formato de áudio",
  "AudioSampleRate": "Taxa de amostragem (áudio)",
  "Author": "Autor",
  "AvgBitrate": "Taxa de bits média",
  "Balance": "Balanço (áudio)",
  "BitDepth": "Profundidade de bits",
  "BitsPerSample": "Bits por amostra",
  "BodySerialNumber": "Número de série do corpo",
  "BrightnessValue": "Valor de brilho",
  "By-line": "Autor",
  "CalibratedFocalLength": "Distância focal calibrada",
  "CalibratedOpticalCenterX": "Centro óptico calibrado X",
  "CalibratedOpticalCenterY": "Centro óptico calibrado Y",
  "CamReverse": "Câmera invertida",
  "CameraOwnerName": "Proprietário da câmera",
  "CameraPitch": "Câmera: arfagem (pitch)",
  "CameraRoll": "Câmera: rolagem (roll)",
  "CameraYaw": "Câmera: guinada (yaw)",
  "Caption-Abstract": "Legenda",
  "Characters": "Caracteres",
  "CharactersWithSpaces": "Caracteres (com espaços)",
  "ChunkOffset": "Posições dos blocos",
  "CircleOfConfusion": "Círculo de confusão",
  "City": "Cidade",
  "ColorComponents": "Componentes de cor",
  "ColorSpace": "Espaço de cor",
  "ColorSpaceData": "Espaço de cor",
  "ColorType": "Tipo de cor",
  "Comment": "Comentário",
  "Company": "Empresa",
  "CompatibleBrands": "Marcas compatíveis",
  "ComponentsConfiguration": "Configuração de componentes",
  "CompositeImage": "Imagem composta",
  "CompressedBitsPerPixel": "Bits por pixel (compressão)",
  "Compression": "Compressão",
  "CompressorID": "Codec (ID)",
  "CompressorName": "Codec",
  "ContentIdentifier": "Identificador de conteúdo",
  "Contrast": "Contraste",
  "Copyright": "Direitos autorais",
  "CopyrightNotice": "Aviso de direitos autorais",
  "Country-PrimaryLocationName": "País",
  "CreateDate": "Data/hora de criação",
  "CreationDate": "Data/hora de criação",
  "CreationTime": "Hora de criação",
  "Creator": "Autor / criador",
  "CreatorTool": "Programa de criação",
  "Credit": "Crédito",
  "CurrentIPTCDigest": "Resumo IPTC atual",
  "CurrentTime": "Tempo atual",
  "CustomRendered": "Processamento personalizado",
  "DOF": "Profundidade de campo",
  "Date": "Data",
  "DateCreated": "Data de criação",
  "DateTimeOriginal": "Data/hora original (captura)",
  "Datecreate": "Data/hora de criação",
  "Datemodify": "Data/hora de modificação",
  "DependentImage1EntryNumber": "Imagem dependente 1 (entrada)",
  "DependentImage2EntryNumber": "Imagem dependente 2 (entrada)",
  "Description": "Descrição",
  "DeviceManufacturer": "Fabricante do dispositivo",
  "DeviceModel": "Modelo do dispositivo",
  "DeviceSettingDescription": "Descrição das configurações do aparelho",
  "DewarpData": "Dados de correção de distorção",
  "DewarpFlag": "Correção de distorção",
  "DigitalZoomRatio": "Zoom digital",
  "DocSecurity": "Segurança do documento",
  "DocumentID": "ID do documento",
  "DocumentStatisticCharacterCount": "Estatística: caracteres",
  "DocumentStatisticImageCount": "Estatística: imagens",
  "DocumentStatisticObjectCount": "Estatística: objetos",
  "DocumentStatisticPageCount": "Estatística: páginas",
  "DocumentStatisticParagraphCount": "Estatística: parágrafos",
  "DocumentStatisticTableCount": "Estatística: tabelas",
  "DocumentStatisticWordCount": "Estatística: palavras",
  "Duration": "Duração",
  "EditingCycles": "Ciclos de edição",
  "EditingDuration": "Duração da edição",
  "Encoder": "Codificador",
  "EncodingProcess": "Processo de codificação",
  "Encryption": "Criptografia",
  "Error": "Erro",
  "ExifByteOrder": "Ordem de bytes do EXIF",
  "ExifImageHeight": "Altura da imagem (EXIF)",
  "ExifImageWidth": "Largura da imagem (EXIF)",
  "ExifVersion": "Versão do EXIF",
  "ExposureCompensation": "Compensação de exposição",
  "ExposureMode": "Modo de exposição",
  "ExposureProgram": "Programa de exposição",
  "ExposureTime": "Tempo de exposição",
  "FNumber": "Número f (abertura)",
  "FOV": "Campo de visão",
  "FileSource": "Origem do arquivo",
  "FileType": "Tipo de arquivo",
  "FileTypeExtension": "Extensão do tipo",
  "Filter": "Filtro",
  "Flash": "Flash",
  "FlashpixVersion": "Versão Flashpix",
  "FlightDegree": "Aeronave: ângulos (°)",
  "FlightPitchDegree": "Aeronave: arfagem (°)",
  "FlightRollDegree": "Aeronave: rolagem (°)",
  "FlightSpeed": "Aeronave: velocidade",
  "FlightXSpeed": "Aeronave: velocidade X",
  "FlightYSpeed": "Aeronave: velocidade Y",
  "FlightYawDegree": "Aeronave: guinada (°)",
  "FlightZSpeed": "Aeronave: velocidade Z",
  "FocalLength": "Distância focal",
  "FocalLength35efl": "Distância focal (equiv. 35 mm)",
  "FocalLengthIn35mmFormat": "Distância focal equivalente (35 mm)",
  "Format": "Formato",
  "GPSAltitude": "Altitude",
  "GPSAltitudeRef": "Referência da altitude",
  "GPSCoordinates": "Coordenadas GPS",
  "GPSDOP": "Precisão (DOP)",
  "GPSDateStamp": "Data GPS (UTC)",
  "GPSDateTime": "Data/hora GPS (UTC)",
  "GPSDestBearing": "Rumo ao destino",
  "GPSDestBearingRef": "Referência do rumo ao destino",
  "GPSDifferential": "Correção diferencial",
  "GPSHPositioningError": "Erro de posição horizontal",
  "GPSImgDirection": "Direção da imagem (bússola)",
  "GPSImgDirectionRef": "Referência da direção da imagem",
  "GPSLatitude": "Latitude",
  "GPSLatitudeRef": "Referência da latitude",
  "GPSLongitude": "Longitude",
  "GPSLongitudeRef": "Referência da longitude",
  "GPSMapDatum": "Datum",
  "GPSMeasureMode": "Modo de medição GPS",
  "GPSPosition": "Posição GPS",
  "GPSProcessingMethod": "Método de posicionamento",
  "GPSSatellites": "Satélites",
  "GPSSpeed": "Velocidade",
  "GPSSpeedRef": "Unidade da velocidade",
  "GPSStatus": "Status do GPS",
  "GPSTimeStamp": "Hora GPS (UTC)",
  "GPSTrack": "Direção do movimento",
  "GPSTrackRef": "Referência da direção do movimento",
  "GPSVersionID": "Versão do GPS",
  "GainControl": "Controle de ganho",
  "Gamma": "Gama",
  "Generator": "Gerador (programa)",
  "Genre": "Gênero",
  "GimbalDegree": "Gimbal: ângulos (°)",
  "GimbalPitchDegree": "Gimbal: arfagem (°)",
  "GimbalReverse": "Gimbal invertido",
  "GimbalRollDegree": "Gimbal: rolagem (°)",
  "GimbalYawDegree": "Gimbal: guinada (°)",
  "GpsStatus": "Status do GPS",
  "GraphicsMode": "Modo gráfico",
  "HEVCConfiguration": "Configuração HEVC (H.265)",
  "HandlerDescription": "Descrição do manipulador",
  "HandlerType": "Tipo de manipulador",
  "HandlerVendorID": "Fornecedor do manipulador",
  "HasCrop": "Tem recorte",
  "HasSettings": "Tem ajustes",
  "HeadingPairs": "Pares de títulos",
  "Histogram": "Histograma",
  "HostComputer": "Computador de origem",
  "HyperfocalDistance": "Distância hiperfocal",
  "HyperlapsDebugInfo": "Depuração interna (hyperlapse)",
  "HyperlinksChanged": "Hiperlinks alterados",
  "ISO": "ISO",
  "ImageDescription": "Descrição da imagem",
  "ImageHeight": "Altura",
  "ImageSize": "Dimensões da imagem",
  "ImageUIDList": "Lista de IDs das imagens",
  "ImageUniqueID": "ID único da imagem",
  "ImageWidth": "Largura",
  "InitialCreator": "Criador inicial",
  "InstanceID": "ID da instância",
  "Interlace": "Entrelaçamento",
  "InteropIndex": "Índice de interoperabilidade",
  "InteropVersion": "Versão de interoperabilidade",
  "JFIFVersion": "Versão JFIF",
  "Keywords": "Palavras-chave",
  "LRFStatus": "Telêmetro: status",
  "LRFTargetAlt": "Telêmetro: altitude do alvo",
  "LRFTargetDistance": "Telêmetro: distância do alvo",
  "LRFTargetLat": "Telêmetro: latitude do alvo",
  "LRFTargetLon": "Telêmetro: longitude do alvo",
  "Language": "Idioma",
  "LastModifiedBy": "Última modificação por",
  "LastPrinted": "Última impressão",
  "LensID": "Lente (identificada)",
  "LensInfo": "Informações da lente",
  "LensMake": "Fabricante da lente",
  "LensModel": "Modelo da lente",
  "LensSerialNumber": "Número de série da lente",
  "LightSource": "Fonte de luz",
  "LightValue": "Valor de luz (LV)",
  "LineCount": "Número de linhas",
  "Linearized": "Otimizado para web (linearizado)",
  "Lines": "Linhas",
  "LinksUpToDate": "Links atualizados",
  "LocationAccuracyHorizontal": "Precisão horizontal da localização",
  "MIMEEncoding": "Codificação de texto",
  "MIMEType": "Tipo MIME",
  "MPFVersion": "Versão MPF",
  "MPImageFlags": "Sinalizadores da imagem",
  "MPImageFormat": "Formato da imagem",
  "MPImageLength": "Tamanho da imagem",
  "MPImageStart": "Início da imagem no arquivo",
  "MPImageType": "Tipo da imagem",
  "MajorBrand": "Marca principal (formato)",
  "Make": "Fabricante",
  "Manager": "Gerente",
  "MatrixStructure": "Matriz de transformação",
  "MaxApertureValue": "Abertura máxima",
  "MediaCreateDate": "Mídia: data/hora de criação",
  "MediaData": "Dados de mídia",
  "MediaDataOffset": "Posição dos dados de mídia",
  "MediaDataSize": "Tamanho dos dados de mídia",
  "MediaDuration": "Mídia: duração",
  "MediaHeaderVersion": "Versão do cabeçalho da mídia",
  "MediaLanguageCode": "Mídia: idioma",
  "MediaModifyDate": "Mídia: data/hora de modificação",
  "MediaTimeScale": "Mídia: escala de tempo",
  "MediaWhitePoint": "Ponto branco da mídia",
  "Megapixels": "Megapixels",
  "MetadataDate": "Data/hora dos metadados",
  "MeteringMode": "Modo de medição",
  "MinorVersion": "Versão secundária",
  "Model": "Modelo",
  "ModifyDate": "Data/hora de modificação",
  "MovieHeaderVersion": "Versão do cabeçalho do filme",
  "Newlines": "Quebras de linha",
  "NextTrackID": "Próximo ID de faixa",
  "NumberOfImages": "Número de imagens",
  "ObjectName": "Título",
  "OffsetTime": "Fuso horário",
  "OffsetTimeDigitized": "Fuso horário (digitalização)",
  "OffsetTimeOriginal": "Fuso horário (captura)",
  "OpColor": "Cor de operação",
  "Orientation": "Orientação",
  "OriginalDocumentID": "ID do documento original",
  "PDFVersion": "Versão do PDF",
  "PageCount": "Número de páginas",
  "PageLayout": "Layout da página",
  "PageMode": "Modo de página",
  "Pages": "Páginas",
  "Paragraphs": "Parágrafos",
  "Pitch": "Arfagem (pitch)",
  "PixelUnits": "Unidade de pixels",
  "PixelsPerUnitX": "Pixels por unidade (X)",
  "PixelsPerUnitY": "Pixels por unidade (Y)",
  "PosterTime": "Tempo do quadro de capa",
  "PreferredRate": "Velocidade preferida",
  "PreferredVolume": "Volume preferido",
  "PreviewDuration": "Duração da prévia",
  "PreviewImage": "Imagem de prévia",
  "PreviewTime": "Início da prévia",
  "PrimaryPlatform": "Plataforma principal",
  "Producer": "Produtor (programa que gerou o PDF)",
  "ProfileCMMType": "CMM do perfil",
  "ProfileClass": "Classe do perfil",
  "ProfileConnectionSpace": "Espaço de conexão",
  "ProfileCopyright": "Direitos do perfil",
  "ProfileCreator": "Criador do perfil",
  "ProfileDateTime": "Data/hora do perfil",
  "ProfileDescription": "Descrição do perfil",
  "ProfileFileSignature": "Assinatura do perfil",
  "ProfileVersion": "Versão do perfil",
  "Province-State": "Estado",
  "Rating": "Classificação",
  "RecommendedExposureIndex": "Índice de exposição recomendado",
  "RelativeAltitude": "Altitude relativa (à decolagem)",
  "RenderingIntent": "Intenção de renderização",
  "ResolutionUnit": "Unidade de resolução",
  "RevisionNumber": "Número de revisão",
  "Rights": "Direitos autorais",
  "Roll": "Rolagem (roll)",
  "Rotation": "Rotação",
  "RtkFlag": "RTK: status",
  "RtkStdHgt": "RTK: desvio padrão da altura",
  "RtkStdLat": "RTK: desvio padrão da latitude",
  "RtkStdLon": "RTK: desvio padrão da longitude",
  "SRGBRendering": "Renderização sRGB",
  "SampleSizes": "Tamanhos das amostras",
  "SampleToChunk": "Amostras por bloco",
  "SamplesPerPixel": "Amostras por pixel",
  "Saturation": "Saturação",
  "ScaleCrop": "Recorte de escala",
  "ScaleFactor35efl": "Fator de corte (35 mm)",
  "SceneCaptureType": "Tipo de captura de cena",
  "SceneType": "Tipo de cena",
  "SelectionDuration": "Duração da seleção",
  "SelectionTime": "Início da seleção",
  "SelfData": "Dados próprios",
  "SensingMethod": "Método de captação",
  "SensitivityType": "Tipo de sensibilidade",
  "SensorID": "ID do sensor",
  "SerialNumber": "Número de série",
  "SharedDoc": "Documento compartilhado",
  "Sharpness": "Nitidez",
  "ShutterSpeed": "Velocidade do obturador",
  "ShutterSpeedValue": "Valor da velocidade do obturador",
  "Software": "Software",
  "Source": "Fonte",
  "SourceImageHeight": "Altura (origem)",
  "SourceImageWidth": "Largura (origem)",
  "SpeedX": "Velocidade X",
  "SpeedY": "Velocidade Y",
  "SpeedZ": "Velocidade Z",
  "SubSecCreateDate": "Data/hora de criação (com subsegundos)",
  "SubSecDateTimeOriginal": "Data/hora original (com subsegundos)",
  "SubSecModifyDate": "Data/hora de modificação (com subsegundos)",
  "SubSecTime": "Subsegundos",
  "SubSecTimeDigitized": "Subsegundos (digitalização)",
  "SubSecTimeOriginal": "Subsegundos (captura)",
  "Subject": "Assunto / palavras-chave",
  "SubjectArea": "Área do objeto",
  "SubjectDistance": "Distância do objeto",
  "SubjectDistanceRange": "Faixa de distância do objeto",
  "SyncSampleTable": "Tabela de quadros-chave",
  "TaggedPDF": "PDF marcado (acessível)",
  "Template": "Modelo",
  "ThumbnailImage": "Miniatura",
  "ThumbnailLength": "Tamanho da miniatura",
  "ThumbnailOffset": "Posição da miniatura",
  "TimeCreated": "Hora de criação",
  "TimeScale": "Escala de tempo",
  "TimeToSampleTable": "Tabela tempo-amostra",
  "Title": "Título",
  "TitlesOfParts": "Títulos das partes",
  "TotalEditTime": "Tempo total de edição",
  "TotalFrames": "Total de quadros",
  "Track": "Faixa nº",
  "TrackCreateDate": "Faixa: data/hora de criação",
  "TrackDuration": "Duração da faixa",
  "TrackHeaderVersion": "Versão do cabeçalho da faixa",
  "TrackID": "ID da faixa",
  "TrackLayer": "Camada da faixa",
  "TrackModifyDate": "Faixa: data/hora de modificação",
  "TrackVolume": "Volume da faixa",
  "Trapped": "Trapping",
  "UserAccess": "Permissões do usuário",
  "UserComment": "Comentário do usuário",
  "Version": "Versão",
  "VideoFrameRate": "Quadros por segundo",
  "Warning": "Aviso",
  "WhiteBalance": "Balanço de branco",
  "WordCount": "Número de palavras",
  "Words": "Palavras",
  "XMPToolkit": "Kit de ferramentas XMP",
  "XPAuthor": "Autor (Windows)",
  "XPComment": "Comentário (Windows)",
  "XPKeywords": "Palavras-chave (Windows)",
  "XPSubject": "Assunto (Windows)",
  "XPTitle": "Título (Windows)",
  "XResolution": "Resolução horizontal",
  "YCbCrPositioning": "Posicionamento YCbCr",
  "YCbCrSubSampling": "Subamostragem YCbCr",
  "YResolution": "Resolução vertical",
  "Yaw": "Guinada (yaw)",
  "Year": "Ano",
  "ZipBitFlag": "ZIP: sinalizadores",
  "ZipCRC": "ZIP: CRC",
  "ZipCompressedSize": "ZIP: tamanho compactado",
  "ZipCompression": "ZIP: compressão",
  "ZipFileName": "ZIP: nome do arquivo",
  "ZipModifyDate": "ZIP: data/hora de modificação",
  "ZipRequiredVersion": "ZIP: versão necessária",
  "ZipUncompressedSize": "ZIP: tamanho descompactado"
  };

const CAMPOS_POR_GRUPO: Record<string, Record<string, string>> = {
  "PDF": {
  "Creator": "Criador (programa de origem)"
  },
  "XML": {
  "Creator": "Autor"
  },
  "XMP-xmp": {
  "CreatorTool": "Programa de criação"
  }
  };

const GRUPOS: Record<string, string> = {
  "APP14": "Adobe (APP14)",
  "Composite": "Calculados pelo exiftool",
  "ExifIFD": "EXIF",
  "File": "Formato do arquivo",
  "FlashPix": "Documento (Office antigo)",
  "GPS": "GPS",
  "ICC-header": "Perfil de cor (ICC): cabeçalho",
  "ICC-meas": "Perfil de cor (ICC): medição",
  "ICC-view": "Perfil de cor (ICC): visualização",
  "ICC_Profile": "Perfil de cor (ICC)",
  "IFD0": "EXIF: imagem principal",
  "IFD1": "EXIF: miniatura",
  "IPTC": "IPTC (legenda e autoria)",
  "InteropIFD": "EXIF: interoperabilidade",
  "ItemList": "Vídeo: lista de itens",
  "JFIF": "JFIF",
  "Keys": "Vídeo: dados do aparelho",
  "MPF0": "Imagens múltiplas (MPF)",
  "PDF": "PDF",
  "PNG": "PNG",
  "Photoshop": "Photoshop",
  "QuickTime": "Vídeo",
  "UserData": "Vídeo: dados do usuário",
  "XML": "Documento",
  "ZIP": "Compactação (ZIP)"
  };

const XMP: Record<string, string> = {
  "GPano": "panorama",
  "crs": "Camera Raw",
  "dc": "Dublin Core",
  "drone-dji": "drone DJI",
  "exif": "EXIF",
  "pdf": "PDF",
  "photoshop": "Photoshop",
  "rdf": "RDF",
  "tiff": "TIFF",
  "x": "kit",
  "xmp": "básico",
  "xmpMM": "histórico de edição"
  };

const FABRICANTES = new Set(["Apple", "Canon", "DJI", "FujiFilm", "GoPro", "Google", "Huawei", "Motorola", "Nikon", "Olympus", "Panasonic", "Pentax", "Ricoh", "Samsung", "Sony", "Xiaomi"]);

const VALORES: Record<string, string> = {
  "Above Sea Level": "Acima do nível do mar",
  "Action (High speed)": "Ação (velocidade alta)",
  "Adaptive": "Adaptativo",
  "Aperture-priority AE": "Prioridade de abertura",
  "Audio Track": "Faixa de áudio",
  "Auto": "Automático",
  "Auto bracket": "Bracketing automático",
  "Auto, Did not fire": "Automático, não disparou",
  "Auto, Fired": "Automático, disparou",
  "Auto, Fired, Red-eye reduction": "Automático, disparou, redução de olhos vermelhos",
  "Average": "Média",
  "Baseline DCT, Huffman coding": "DCT básico, codificação Huffman",
  "Below Sea Level": "Abaixo do nível do mar",
  "Big-endian (Motorola, MM)": "Big-endian (Motorola, MM)",
  "Center-weighted average": "Média ponderada ao centro",
  "Centered": "Centralizado",
  "Cloudy": "Nublado",
  "Co-sited": "Coincidente (co-sited)",
  "Creative (Slow speed)": "Criativo (velocidade baixa)",
  "Custom": "Personalizado",
  "Data Handler": "Manipulador de dados",
  "Daylight": "Luz do dia",
  "Deflate/Inflate": "Deflate",
  "Digital Camera": "Câmera digital",
  "Directly photographed": "Fotografado diretamente",
  "East": "Leste",
  "False": "Não",
  "Fine Weather": "Tempo bom",
  "Fired": "Disparou",
  "Fluorescent": "Fluorescente",
  "Grayscale": "Tons de cinza",
  "Hard": "Forte",
  "High": "Alto",
  "High gain up": "Ganho alto (aumento)",
  "Horizontal (normal)": "Horizontal (normal)",
  "JPEG (old-style)": "JPEG (estilo antigo)",
  "Landscape": "Paisagem",
  "Little-endian (Intel, II)": "Little-endian (Intel, II)",
  "Low": "Baixo",
  "Low gain up": "Ganho baixo (aumento)",
  "Magnetic North": "Norte magnético",
  "Manual": "Manual",
  "Media Handler": "Manipulador de mídia",
  "Metadata Tags": "Metadados",
  "Mirror horizontal": "Espelhada na horizontal",
  "Mirror vertical": "Espelhada na vertical",
  "Multi-segment": "Matricial (multissegmento)",
  "Multi-spot": "Multipontual",
  "Night": "Noturna",
  "No": "Não",
  "No Flash": "Sem flash",
  "No flash function": "Sem função de flash",
  "None": "Nenhum",
  "Noninterlaced": "Sem entrelaçamento",
  "Normal": "Normal",
  "North": "Norte",
  "Not Defined": "Não definido",
  "Off, Did not fire": "Desligado, não disparou",
  "Off, Did not fire, Return not detected": "Desligado, não disparou",
  "On, Fired": "Ligado, disparou",
  "One-chip color area": "Sensor de área colorida (um chip)",
  "Other": "Outro",
  "Palette": "Paleta",
  "Partial": "Parcial",
  "Perceptual": "Perceptual",
  "Portrait": "Retrato",
  "Program AE": "Programa automático (AE)",
  "Progressive DCT, Huffman coding": "DCT progressivo, codificação Huffman",
  "RGB": "RGB",
  "RGB with Alpha": "RGB com transparência",
  "Rotate 180": "Girada 180°",
  "Rotate 270 CW": "Girada 270° (sentido horário)",
  "Rotate 90 CW": "Girada 90° (sentido horário)",
  "Shade": "Sombra",
  "Shutter speed priority AE": "Prioridade de velocidade",
  "Soft": "Suave",
  "South": "Sul",
  "Spot": "Pontual",
  "Standard": "Padrão",
  "True": "Sim",
  "True North": "Norte verdadeiro",
  "Tungsten (Incandescent)": "Tungstênio (incandescente)",
  "Uncalibrated": "Não calibrado",
  "Uncompressed": "Sem compressão",
  "Unknown": "Desconhecido",
  "Video Track": "Faixa de vídeo",
  "West": "Oeste",
  "Yes": "Sim",
  "cm": "centímetros",
  "inches": "polegadas",
  "km/h": "km/h",
  "meters": "metros",
  "sRGB": "sRGB",
  "srcCopy": "Cópia direta (srcCopy)"
  };

export function grupoPt(g: string): string {
  if (GRUPOS[g]) return GRUPOS[g]!;
  const x = /^XMP-(.+)$/.exec(g);
  if (x) return `XMP: ${XMP[x[1]!] ?? x[1]}`;
  let n = /^MPImage(\d+)$/.exec(g);
  if (n) return `Imagem embutida ${n[1]}`;
  n = /^Track(\d+)$/.exec(g);
  if (n) return `Faixa ${n[1]}`;
  if (FABRICANTES.has(g)) return `Notas do fabricante (${g})`;
  return g;
}

/** "GimbalReverse" → "Gimbal Reverse", para o que não está no dicionário. */
function separar(nome: string): string {
  return nome
    .replace(/_/g, " ")
    .replace(/([a-z])([A-Z])/g, "$1 $2")
    .replace(/([A-Z])([A-Z][a-z])/g, "$1 $2")
    .replace(/([A-Za-z])(\d)/g, "$1 $2");
}

export function campoPt(nome: string, grupo?: string): string {
  const g = grupo ? CAMPOS_POR_GRUPO[grupo] : undefined;
  if (g?.[nome]) return g[nome]!;
  if (CAMPOS[nome]) return CAMPOS[nome]!;
  const bloco = /^Unknown_(.+)$/.exec(nome);
  if (bloco) return `Bloco desconhecido (${bloco[1]})`;
  return separar(nome);
}

/** "2026:05:26 18:04:30.123-03:00" → "26/05/2026 18:04:30,123 (-03:00)" */
function data(v: string): string | null {
  const m = /^(\d{4}):(\d{2}):(\d{2})(.*)$/.exec(v);
  if (!m) return null;
  const [, a, mo, d, resto] = m as unknown as [string, string, string, string, string];
  if (a === "0000") return `${v} (sem data)`;
  if (resto === "") return `${d}/${mo}/${a}`;
  const t = /^ (\d{2}:\d{2}:\d{2})([.,]?\d*)(.*)$/.exec(resto);
  if (!t) return null;
  let s = `${d}/${mo}/${a} ${t[1]}`;
  if (t[2]) s += `,${t[2].slice(1)}`;
  const fuso = t[3] ?? "";
  if (fuso === "Z") s += " (UTC)";
  else if (/^[+-]\d{2}:\d{2}$/.test(fuso)) s += ` (${fuso})`;
  else if (fuso) s += fuso;
  return s;
}

export function valorPt(v: string): string {
  if (VALORES[v]) return VALORES[v]!;
  const d = data(v);
  if (d) return d;
  return v
    .replace(/(\d) deg /g, "$1° ")
    .replace(/(\d) deg$/, "$1°")
    .replace(/Above Sea Level/g, "acima do nível do mar")
    .replace(/Below Sea Level/g, "abaixo do nível do mar")
    .replace(/^\(Binary data (\d+) bytes, use -b option to extract\)$/, "(dados binários: $1 bytes; extrair com exiftool -b)");
}
